const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const examplePath = path.join(__dirname, '.env.example');

console.log('\n🚀 Starting AntCapture Setup...');

if (!fs.existsSync(envPath)) {
  if (fs.existsSync(examplePath)) {
    fs.copyFileSync(examplePath, envPath);
    console.log('✅ Created root .env from .env.example');
    console.log('⚠️  Please edit the .env file with your specific settings, then run `npm run setup` again.');
    process.exit(0);
  } else {
    console.error('❌ Could not find .env.example!');
    process.exit(1);
  }
}

// Parse root .env
const envContent = fs.readFileSync(envPath, 'utf8');
const env = {};
envContent.split('\n').forEach(line => {
  const match = line.match(/^\s*([\w\.\-]+)\s*=\s*(.*)?\s*$/);
  if (match) {
    env[match[1]] = match[2] ? match[2].trim() : '';
  }
});

const storageServer = env.STORAGE_BACKEND || 'local';
const serverUrl = env.SERVER_URL || 'http://localhost:3001';
const webUiUrl = env.WEB_UI_URL || 'http://localhost:5173';

// 1. Generate Server .env
const serverEnvPath = path.join(__dirname, 'server', '.env');
const serverEnvContent = `
# Auto-generated by setup.js
STORAGE_BACKEND=${storageServer}
GOOGLE_CLIENT_ID=${env.GOOGLE_CLIENT_ID || ''}
GOOGLE_CLIENT_SECRET=${env.GOOGLE_CLIENT_SECRET || ''}
GOOGLE_REDIRECT_URI=${serverUrl}/auth/callback
JWT_SECRET=${env.JWT_SECRET || 'fallback_secret'}

# Database connection (PostgreSQL for drive, SQLite for local)
${storageServer === 'local' ? 'DATABASE_URL="file:./antcapture.db"' : `DATABASE_URL="${env.DATABASE_URL || ''}"`}
`;
fs.writeFileSync(serverEnvPath, serverEnvContent.trim());
console.log('✅ Updated server/.env');

// 2. Generate Web UI .env
const webUiEnvPath = path.join(__dirname, 'web-ui', '.env');
const webUiEnvContent = `
# Auto-generated by setup.js
VITE_API_BASE_URL=${serverUrl}
`;
fs.writeFileSync(webUiEnvPath, webUiEnvContent.trim());
console.log('✅ Updated web-ui/.env');

// 3. Generate Extension Config
const extConfigPath = path.join(__dirname, 'extension', 'config.js');
const extConfigContent = \`
// Auto-generated by setup.js
export const DEV_SERVER_URL  = 'http://localhost:3001';
export const PROD_SERVER_URL = '\${serverUrl}';
export const DEV_WEB_UI_URL   = 'http://localhost:5173';
export const PROD_WEB_UI_URL  = '\${webUiUrl}';
\`;
fs.writeFileSync(extConfigPath, extConfigContent.trim());
console.log('✅ Updated extension/config.js');

console.log('🎉 Setup Complete! You can now run `npm run dev:all` or start individual services.\n');
