// Auto-generated by setup.js
export const DEV_BACKEND_URL  = 'http://localhost:3001';
export const PROD_BACKEND_URL = 'https://api.antcapture.anttake.com';
export const DEV_WEB_UI_URL   = 'http://localhost:5173';
export const PROD_WEB_UI_URL  = 'https://antcapture.anttake.com';
